version: '3'
services:
  app:
    container_name: disbursement_service
    build: .
    ports:
      - 8080:8080
    restart: on-failure
    depends_on:
      - disbursement_db
  disbursement_db:
    container_name: disbursement_db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'ewallet'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'pass'
      MYSQL_ROOT_PASSWORD: 'pass'
    ports:
      - '3306:3306'
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db:
